/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Product } from "./components/global/store";
export { Product } from "./components/global/store";
export namespace Components {
    interface StencilCartIcon {
    }
    interface StencilCartModal {
    }
    interface StencilProductCard {
        "product": string | Product | Product[];
    }
}
declare global {
    interface HTMLStencilCartIconElement extends Components.StencilCartIcon, HTMLStencilElement {
    }
    var HTMLStencilCartIconElement: {
        prototype: HTMLStencilCartIconElement;
        new (): HTMLStencilCartIconElement;
    };
    interface HTMLStencilCartModalElement extends Components.StencilCartModal, HTMLStencilElement {
    }
    var HTMLStencilCartModalElement: {
        prototype: HTMLStencilCartModalElement;
        new (): HTMLStencilCartModalElement;
    };
    interface HTMLStencilProductCardElement extends Components.StencilProductCard, HTMLStencilElement {
    }
    var HTMLStencilProductCardElement: {
        prototype: HTMLStencilProductCardElement;
        new (): HTMLStencilProductCardElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-cart-icon": HTMLStencilCartIconElement;
        "stencil-cart-modal": HTMLStencilCartModalElement;
        "stencil-product-card": HTMLStencilProductCardElement;
    }
}
declare namespace LocalJSX {
    interface StencilCartIcon {
    }
    interface StencilCartModal {
    }
    interface StencilProductCard {
        "product"?: string | Product | Product[];
    }
    interface IntrinsicElements {
        "stencil-cart-icon": StencilCartIcon;
        "stencil-cart-modal": StencilCartModal;
        "stencil-product-card": StencilProductCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-cart-icon": LocalJSX.StencilCartIcon & JSXBase.HTMLAttributes<HTMLStencilCartIconElement>;
            "stencil-cart-modal": LocalJSX.StencilCartModal & JSXBase.HTMLAttributes<HTMLStencilCartModalElement>;
            "stencil-product-card": LocalJSX.StencilProductCard & JSXBase.HTMLAttributes<HTMLStencilProductCardElement>;
        }
    }
}
